CREATE TABLE IF NOT EXISTS ratings
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    email    VARCHAR(255) UNIQUE NOT NULL,
    login    VARCHAR(255) UNIQUE NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date DATE,
    duration     INTEGER      NOT NULL CHECK (duration > 0),
    rating_id    INTEGER      REFERENCES ratings (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  BIGINT REFERENCES films (id) ON DELETE CASCADE,
    genre_id BIGINT REFERENCES genres (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friendships
(
    requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    receiver_id  BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR(50) NOT NULL CHECK (status IN ('UNCONFIRMED', 'CONFIRMED')),
    PRIMARY KEY (requester_id, receiver_id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id BIGINT REFERENCES films (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);